Fix #489
jazzband/tablib pull request #490
Opened 2021-02-28 20:44 UTC by mpasternak

Make sure there are no bad characters in sheet names!

2021-02-28 21:29 UTC, claudep requested changes
Could you please include a small description in the commit first line, after the issue number?

2021-02-28 21:29 UTC, claudep commented on src/tablib/formats/_xlsx.py
> +
I guess those two lines should not be in the patch.

2021-03-01 08:19 UTC, mpasternak commented on src/tablib/formats/_xlsx.py
> +
Updated, thanks

2021-03-01 08:21 UTC, mpasternak commented
> Could you please include a small description in the commit first line, after the issue number?

I am not sure if I understand, what you mean. 

Do you want me to change the commit message? Is this even possible? If it is, I have no idea how can I do that. 

I could re-write everything (as this is a very small update) and re-commit with a better message, but is that what you want from me? 

Please explain. I am willing to work with you on this patch but I am not sure if I understood correctly.

2021-03-01 08:27 UTC, claudep commented
Exactly, I'd like a small description of the change in the commit message.

You can do that by:
`git commit --amend` (and editing the message)
Then force push your branch:
`git push -f <repo-alias> master`

2021-03-01 09:00 UTC, claudep commented
Oh sorry, now I realize that you have several commits already. So you should use some rebase magic to do that.

`git rebase -i HEAD~3` would allow you to re-edit the commit message. I'd suggest you to study a bit the rebase capabilities, as it could surely be useful in your projects. Of course, rebasing should be done with caution and only on "working" branches.

2021-03-01 12:08 UTC, mpasternak commented
I did rebase and a force-push. Does it look okay for you?

2021-03-01 12:38 UTC, claudep approved these changes
Perfect, thanks a lot!

2021-03-01 12:38 UTC, merged